name: update
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"
env:
  SOURCE_NAME: gerbv
  SOURCE_DIR: ${{ github.workspace }}/submodules/gerbv
jobs:
  update:
    runs-on: "ubuntu-16.04"
    steps:
      - name: "production: checkout project"
        if: env.GITHUB_ACTOR != 'nektos/act'
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: ${{ github.workspace }}
          fetch-depth: 0
          submodules: recursive

      - name: "production: setup"
        if: env.GITHUB_ACTOR != 'nektos/act'
        run: ${{ github.workspace }}/ci/setup

      - name: "git setup"
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" git config --global user.name "github-actions[bot]"

      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 14

      - name: "set build tag"
        id: set_build_tag
        run: (cd "${GITHUB_WORKSPACE}/ci" && npm install && ./scripts/set_build_tag.js)

      - name: "build"
        id: build
        if: steps.set_build_tag.outputs.build_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_TAG_SOURCE: ${{ steps.set_build_tag.outputs.build_source_tag }}
          BUILD_TAG: ${{ steps.set_build_tag.outputs.build_tag }}
        run: cd "${SOURCE_DIR}" && ${{ github.workspace }}/ci/scripts/build.sh

      - name: "dev: success - early termination"
        if: env.GITHUB_ACTOR == 'nektos/act'
        run: echo "AppImage_path=${{ steps.build.outputs.AppImage_path }}"; echo "Success! Exiting with failure code for early termination in development..."; exit 1;

      - name: "update AppImage_url"
        env:
          BUILD_TAG_SOURCE: ${{ steps.set_build_tag.outputs.build_source_tag }}
          BUILD_TAG: ${{ steps.set_build_tag.outputs.build_tag }}
        run: echo "https://github.com/m59peacemaker/gerbv-appimage/releases/download/${BUILD_TAG}/Gerbv_Gerber_File_Viewer-${BUILD_TAG_SOURCE}-x86_64.AppImage" > AppImage_url

      - name: "update node package"
        run: npm version --force "${{ steps.set_build_tag.outputs.build_tag }}"

      - name: "commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.set_build_tag.outputs.build_tag }}
          file_pattern: package.json AppImage_url

      - name: "create release"
        id: create_release
        if: steps.build.outputs.AppImage_path
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.set_build_tag.outputs.build_tag }}
          release_name: ${{ steps.set_build_tag.outputs.build_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "upload release AppImage"
        id: upload_appimage
        if: steps.create_release.outputs.upload_url && steps.build.outputs.AppImage_path
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.AppImage_path }}
          asset_name: ${{ steps.build.outputs.AppImage_name }}
          asset_content_type: application/vnd.appimage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
